# Generated by Django 3.0.8 on 2020-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MY Created WebApp', max_length=255),
        ),
    ]
