# Generated by Django 3.0.8 on 2020-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_auto_20200720_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Now you can create your won snippet for your article', max_length=100),
        ),
    ]
